# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

Classes = [
    {
        "cid": "{0ba81119-3b86-44f5-9de7-322d96e13627}",
        "contract_ids": ["@mozilla.org/security/lockstore;1"],
        "type": "mozilla::security::lockstore::LockstoreService",
        "headers": ["/security/lockstore/LockstoreService.h"],
        "init_method": "Init",
        "singleton": True,
    },
    {
        "cid": "{4f1ac573-bee9-4d2b-8a5e-c8d7a2f3b4e1}",
        "contract_ids": ["@mozilla.org/security/bip39;1"],
        "type": "mozilla::security::lockstore::Bip39Service",
        "headers": ["/security/lockstore/Bip39Service.h"],
        "singleton": True,
    },
]
